# Generated by Django 3.2.12 on 2023-08-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='keywords',
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
